blank_issues_enabled: false
contact_links:
  - name: Questions
    url: https://github.com/ConGodsted/PuzzlesLibForked
    about: "Please do not contact Fuzs about supporting this unofificial backport!"